### ISSUE TITLE
Missing an environment from solenopsis.ENVIRONMENTS makes things go wrong

### ISSUE THREAD

**Issue by pcon** [solenopsis/Solenopsis#207]
If you add a new environment to `~/.solenopsis/credentials/` and then pass it as the `solenopsis.env.DEPENDENT` things go off the rails for any push call.  This is fixed by adding the environment name to `solenopsis.ENVIRONMENTS`  We should either make a use the `solenopsis.env.local.HOME` for all environments if we cannot find their home, or we should error out stating that it's an unknown environment or that it could not be found in solenopsis.ENVIRONMENTS

**Comment by sfloess** [comment]
@pcon absolutely agree.  This is a craptastic bug ;)

**Comment by sfloess** [comment]
@pcon I just tried this:

```bash
cp ~/.solenopsis/credentials/sfloess.properties ~/.solenopsis/credentials/alphaBeta.properties
bsolenopsis -Dsolenopsis.env.DEPENDENT=alphaBeta push
```

The push ran as one normally expects.  My ~/solenopsis.properties looks like so:

```properties
solenopsis.ENVIRONMENTS=sfloess dev pconnell jhird
solenopsis.env.HOME=/home/sfloess/.solenopsis
solenopsis.env.MASTER=local
solenopsis.env.DEPENDENT=sfloess
solenopsis.env.local.HOME=/home/sfloess/Development/redhat/GSS/CCM/ccm/src

sf.xslDir=/home/sfloess/Development/redhat/GSS/CCM/ccm/xslt/solenopsis
sf.ignoreFile = /home/sfloess/Development/redhat/GSS/CCM/ccm/.sfdcignore
```

What did you see and which commands did you execute?

**Comment by pcon** [comment]
Running

`java -Dant.home=/usr/share/solenopsis/ant org.apache.tools.ant.Main  -Dsolenopsis.env.DEPENDENT='foo' -f /usr/share/solenopsis/ant/solenopsis.xml delta-push`

causes this error

```text
BUILD FAILED
/usr/share/solenopsis/ant/1.1/solenopsis-build.xml:224: The following error occurred while executing this line:
/usr/share/solenopsis/ant/1.1/util/sfdc-util.xml:2840: org.apache.bsf.BSFException: BeanShell script error: Sourced file: inline evaluation of: ``                                                                                                        import java.io.File;               import java.io.Ra . . . '' : Typed variable declaration : The collection, array, map, iterator, or enumeration portion of a for statement cannot be null. : at Line: 38 : in file: inline evaluation of: ``                                                                                                      import java.io.File;               import java.io.Ra . . . '' : for ( String fileName : dir .list ( ) ) {

Called from method: gatherFiles : at Line: 159 : in file: inline evaluation of: ``                                                                                                       import java.io.File;               import java.io.Ra . . . '' : gatherFiles ( computeIgnorePattern ( ) , attributes .get ( "dest" ) )  BSF info: scriptdef_http://www.redhat.com/util:dirDiff at line: 0 column: columnNo
     at bsh.util.BeanShellBSFEngine.eval(Unknown Source)
     at bsh.util.BeanShellBSFEngine.exec(Unknown Source)
     at org.apache.bsf.BSFManager$6.run(BSFManager.java:493)
     at java.security.AccessController.doPrivileged(Native Method)
     at org.apache.bsf.BSFManager.exec(BSFManager.java:491)
     at org.apache.tools.ant.util.optional.ScriptRunner.executeScript(ScriptRunner.java:98)
     at org.apache.tools.ant.taskdefs.optional.script.ScriptDef.executeScript(ScriptDef.java:349)
     at org.apache.tools.ant.taskdefs.optional.script.ScriptDefBase.execute(ScriptDefBase.java:51)
     at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
     at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     at java.lang.reflect.Method.invoke(Method.java:606)
     at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
     at org.apache.tools.ant.Task.perform(Task.java:348)
     at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:68)
     at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
     at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     at java.lang.reflect.Method.invoke(Method.java:606)
     at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
     at org.apache.tools.ant.Task.perform(Task.java:348)
     at org.apache.tools.ant.taskdefs.MacroInstance.execute(MacroInstance.java:396)
     at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
     at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     at java.lang.reflect.Method.invoke(Method.java:606)
     at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
     at org.apache.tools.ant.Task.perform(Task.java:348)
     at org.apache.tools.ant.Target.execute(Target.java:435)
     at org.apache.tools.ant.Target.performTasks(Target.java:456)
     at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
     at org.apache.tools.ant.Project.executeTarget(Project.java:1376)
     at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
     at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
     at org.apache.tools.ant.Main.runBuild(Main.java:853)
     at org.apache.tools.ant.Main.startAnt(Main.java:235)
     at org.apache.tools.ant.Main.start(Main.java:198)
     at org.apache.tools.ant.Main.main(Main.java:286)
```

It also creates a folder `ant/${solenopsis.env.foo.HOME}/` in my solenopsis dir (not installed as root but in my users' home dir)

_Full stack trace_
```text
cached-delta-push:
[rh-util:dirDiff] Jan 12, 2016 1:27:43 PM org.apache.bsf.BSFManager exec
[rh-util:dirDiff] SEVERE: Exception :
[rh-util:dirDiff] java.security.PrivilegedActionException: org.apache.bsf.BSFException: BeanShell script error: Sourced file: inline evaluation of: ``                                                                                                         import java.io.File;               import java.io.Ra . . . '' : Typed variable declaration : The collection, array, map, iterator, or enumeration portion of a for statement cannot be null. : at Line: 38 : in file: inline evaluation of: ``                                                                                                      import java.io.File;               import java.io.Ra . . . '' : for ( String fileName : dir .list ( ) ) {
[rh-util:dirDiff]
[rh-util:dirDiff] Called from method: gatherFiles : at Line: 159 : in file: inline evaluation of: ``                                                                                                         import java.io.File;               import java.io.Ra . . . '' : gatherFiles ( computeIgnorePattern ( ) , attributes .get ( "dest" ) )  BSF info: scriptdef_http://www.redhat.com/util:dirDiff at line: 0 column: columnNo
[rh-util:dirDiff]   at java.security.AccessController.doPrivileged(Native Method)
[rh-util:dirDiff]   at org.apache.bsf.BSFManager.exec(BSFManager.java:491)
[rh-util:dirDiff]   at org.apache.tools.ant.util.optional.ScriptRunner.executeScript(ScriptRunner.java:98)
[rh-util:dirDiff]   at org.apache.tools.ant.taskdefs.optional.script.ScriptDef.executeScript(ScriptDef.java:349)
[rh-util:dirDiff]   at org.apache.tools.ant.taskdefs.optional.script.ScriptDefBase.execute(ScriptDefBase.java:51)
[rh-util:dirDiff]   at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
[rh-util:dirDiff]   at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
[rh-util:dirDiff]   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[rh-util:dirDiff]   at java.lang.reflect.Method.invoke(Method.java:606)
[rh-util:dirDiff]   at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
[rh-util:dirDiff]   at org.apache.tools.ant.Task.perform(Task.java:348)
[rh-util:dirDiff]   at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:68)
[rh-util:dirDiff]   at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
[rh-util:dirDiff]   at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
[rh-util:dirDiff]   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[rh-util:dirDiff]   at java.lang.reflect.Method.invoke(Method.java:606)
[rh-util:dirDiff]   at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
[rh-util:dirDiff]   at org.apache.tools.ant.Task.perform(Task.java:348)
[rh-util:dirDiff]   at org.apache.tools.ant.taskdefs.MacroInstance.execute(MacroInstance.java:396)
[rh-util:dirDiff]   at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
[rh-util:dirDiff]   at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
[rh-util:dirDiff]   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[rh-util:dirDiff]   at java.lang.reflect.Method.invoke(Method.java:606)
[rh-util:dirDiff]   at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
[rh-util:dirDiff]   at org.apache.tools.ant.Task.perform(Task.java:348)
[rh-util:dirDiff]   at org.apache.tools.ant.Target.execute(Target.java:435)
[rh-util:dirDiff]   at org.apache.tools.ant.Target.performTasks(Target.java:456)
[rh-util:dirDiff]   at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
[rh-util:dirDiff]   at org.apache.tools.ant.Project.executeTarget(Project.java:1376)
[rh-util:dirDiff]   at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
[rh-util:dirDiff]   at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
[rh-util:dirDiff]   at org.apache.tools.ant.Main.runBuild(Main.java:853)
[rh-util:dirDiff]   at org.apache.tools.ant.Main.startAnt(Main.java:235)
[rh-util:dirDiff]   at org.apache.tools.ant.Main.start(Main.java:198)
[rh-util:dirDiff]   at org.apache.tools.ant.Main.main(Main.java:286)
[rh-util:dirDiff] Caused by: org.apache.bsf.BSFException: BeanShell script error: Sourced file: inline evaluation of: ``                                                                                                         import java.io.File;               import java.io.Ra . . . '' : Typed variable declaration : The collection, array, map, iterator, or enumeration portion of a for statement cannot be null. : at Line: 38 : in file: inline evaluation of: ``                                                                                                      import java.io.File;               import java.io.Ra . . . '' : for ( String fileName : dir .list ( ) ) {
[rh-util:dirDiff]
[rh-util:dirDiff] Called from method: gatherFiles : at Line: 159 : in file: inline evaluation of: ``                                                                                                         import java.io.File;               import java.io.Ra . . . '' : gatherFiles ( computeIgnorePattern ( ) , attributes .get ( "dest" ) )  BSF info: scriptdef_http://www.redhat.com/util:dirDiff at line: 0 column: columnNo
[rh-util:dirDiff]   at bsh.util.BeanShellBSFEngine.eval(Unknown Source)
[rh-util:dirDiff]   at bsh.util.BeanShellBSFEngine.exec(Unknown Source)
[rh-util:dirDiff]   at org.apache.bsf.BSFManager$6.run(BSFManager.java:493)
[rh-util:dirDiff]   ... 35 more
[rh-util:dirDiff]
```

**Comment by sfloess** [comment]
@pcon - thank you!  I can repro this now :+1:

**Comment by sfloess** [comment]
The fix (looks like it's solely related to the various pulls) is to ensure that ```${solenopsis.env.@{dependentEnv}.HOME}``` actually expands to something correctly.  For example if dependentEnv is ```fooBar```, expanded we should *not* see ```${solenopsis.env.fooBar.HOME}```.

**Comment by sfloess** [comment]
Results of testing:

```bash
bsolenopsis -Dsolenopsis.env.DEPENDENT=alphaBeta delta-push
...
/home/sfloess/Development/github/solenopsis/Solenopsis/ant/1.1/util/sfdc-util.xml:1870: Please define [alphaBeta] in solenopsis.ENVIRONMENTS!!!
```

```bash
bsolenopsis -Dsolenopsis.env.DEPENDENT=alphaBeta destructive-push
...
pull-full:

BUILD FAILED
...
/home/sfloess/Development/github/solenopsis/Solenopsis/ant/1.1/util/sfdc-util.xml:1870: Please define [alphaBeta] in solenopsis.ENVIRONMENTS!!!
```

```bash
bsolenopsis -Dsolenopsis.env.DEPENDENT=alphaBeta pull
...
pull:

BUILD FAILED
...
/home/sfloess/Development/github/solenopsis/Solenopsis/ant/1.1/util/sfdc-util.xml:1735: Please define [alphaBeta] in solenopsis.ENVIRONMENTS!!!
```

```bash
bsolenopsis -Dsolenopsis.env.DEPENDENT=alphaBeta pull-full
...
pull-full:

BUILD FAILED
...
/home/sfloess/Development/github/solenopsis/Solenopsis/ant/1.1/util/sfdc-util.xml:1870: Please define [alphaBeta] in solenopsis.ENVIRONMENTS!!!
