### ISSUE TITLE
com.sforce.ws.ConnectionException: Failed to parse detail:  START_TAG seen ...

### ISSUE THREAD

**Issue by congyunchen** [solenopsis/Solenopsis#238]
I'm not sure the problem.Initially thought it was TLSv1.0 version problem.
now,TLS is V1.1 or V1.2.There is still a problem.

com.sforce.ws.ConnectionException: Failed to parse detail:  START_TAG seen ...</sf:exceptionMessage><sf:upgradeURL>... @1:637 due to: com.sforce.ws.ConnectionException: unable to find end tag at:  START_TAG seen ...</sf:exceptionMessage><sf:upgradeURL>... @1:637
	at com.sforce.ws.transport.SoapConnection.parseDetail(SoapConnection.java:246)
	at com.sforce.ws.transport.SoapConnection.createException(SoapConnection.java:210)
	at com.sforce.ws.transport.SoapConnection.receive(SoapConnection.java:156)
	at com.sforce.ws.transport.SoapConnection.send(SoapConnection.java:99)
	at com.sforce.soap.enterprise.EnterpriseConnection.login(EnterpriseConnection.java:1115)
	at com.sforce.soap.enterprise.EnterpriseConnection.<init>(EnterpriseConnection.java:386)
	at com.sforce.soap.enterprise.Connector.newConnection(Connector.java:27)
	at app.movittech.envisioneye.job.Test.main(Test.java:79)

java -version
java version "1.7.0_79"
Java(TM) SE Runtime Environment (build 1.7.0_79-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.79-b02, mixed mode)

**Comment by pcon** [comment]
The first thing that pops into my head is possibly a password with an XML reserved character. It should be escaped, but that's the first thing.

Please provide the command you're using. If you're using the solenopsis wrapper script, you can use --dump-files to write the package.xml to disk to look for abnormalities.

**Comment by sfloess** [comment]
@congyunchen - pretty sure this is the TLS thing:  http://salesforce.stackexchange.com/questions/140574/getting-the-com-sforce-ws-connectionexception-failed-to-parse-detail-start-ta

I was running an appserver today without the TLS options and was seeing similar issues.  Mind showing me what you are doing when you call Solenopsis?

**Comment by sfloess** [comment]
Closing this since I do believe it is a TLS issue and haven't heard back.
