### ISSUE TITLE
Support "sharing" metadata for pulls 

### ISSUE THREAD

**Issue by sfloess** [solenopsis/Solenopsis#266]
Support [sharing metadata](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/manifest_samples.htm#manifest_sharing) for pulls in package.xml

[Rules](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_sharingrules.htm)

**Comment by flossy-redhat** [comment]
@pcon - mind testing the branch sfloess_266?

I do see this when running (which I believe has nothing to do with this recent change):
```
[sf:retrieve] package.xml - Entity of type 'CustomObject' named 'EntityMilestone' cannot be found
[sf:retrieve] package.xml - Entity of type 'CustomObject' named 'SnapshotAuditEvent' cannot be found
[sf:retrieve] package.xml - Entity of type 'CustomObject' named 'Question' cannot be found
[sf:retrieve] package.xml - Entity of type 'CustomObject' named 'SnapshotBin' cannot be found
[sf:retrieve] package.xml - Entity of type 'CustomObject' named 'QuickTextAction' cannot be found
[sf:retrieve] package.xml - Entity of type 'CustomObject' named 'SnapshotConfig' cannot be found
[sf:retrieve] package.xml - Entity of type 'CustomObject' named 'Reply' cannot be found
[sf:retrieve] package.xml - Entity type 'GlobalPicklist' is not available in this api version
[sf:retrieve] package.xml - Entity type: 'LiveChatSensitiveDataRules' is unknown
[sf:retrieve] package.xml - Unable to retrieve file for id 54 (QuoteStatus). This Standard Value Set is either inaccessible or not supported in Metadata API.
[sf:retrieve] package.xml - Unable to retrieve file for id 62 (IdeaThemeStatus). This Standard Value Set is either inaccessible or not supported in Metadata API.
[sf:retrieve] package.xml - Unable to retrieve file for id 63 (AddressStateCode). This Standard Value Set is either inaccessible or not supported in Metadata API.
[sf:retrieve] package.xml - Unable to retrieve file for id 64 (AddressCountryCode). This Standard Value Set is either inaccessible or not supported in Metadata API.
[sf:retrieve] package.xml - Unable to retrieve file for id 29 (InvoiceStatus). This Standard Value Set is either inaccessible or not supported in Metadata API.
[sf:retrieve] package.xml - Unable to retrieve file for id 70 (AccountContactMultiRoles). This Standard Value Set is either inaccessible or not supported in Metadata API.
[sf:retrieve] package.xml - Unable to retrieve file for id 71 (WorkOrderStatus). This Standard Value Set is either inaccessible or not supported in Metadata API.
[sf:retrieve] package.xml - Unable to retrieve file for id 72 (WorkOrderLineItemPriority). This Standard Value Set is either inaccessible or not supported in Metadata API.
[sf:retrieve] package.xml - Unable to retrieve file for id 73 (WorkOrderLineItemStatus). This Standard Value Set is either inaccessible or not supported in Metadata API.
[sf:retrieve] package.xml - Unable to retrieve file for id 37 (OrderType). This Standard Value Set is either inaccessible or not supported in Metadata API.
[sf:retrieve] package.xml - Can't retrieve non-customizable CustomObject named: UserLicense
```

I can remove them if you ack...

**Comment by sfloess** [comment]
Looking at Jenkins deploys (for QA), I see this in the console :
```
[sf:retrieve] package.xml - Entity of type 'CustomObject' named 'EntityMilestone' cannot be found
[sf:retrieve] package.xml - Entity of type 'CustomObject' named 'SnapshotAuditEvent' cannot be found
[sf:retrieve] package.xml - Entity of type 'CustomObject' named 'Question' cannot be found
[sf:retrieve] package.xml - Entity of type 'CustomObject' named 'SnapshotBin' cannot be found
[sf:retrieve] package.xml - Entity of type 'CustomObject' named 'QuickTextAction' cannot be found
[sf:retrieve] package.xml - Entity of type 'CustomObject' named 'SnapshotConfig' cannot be found
[sf:retrieve] package.xml - Entity of type 'CustomObject' named 'Reply' cannot be found
[sf:retrieve] package.xml - Entity type 'GlobalPicklist' is not available in this api version
[sf:retrieve] package.xml - Unable to retrieve file for id 54 (QuoteStatus). This Standard Value Set is either inaccessible or not supported in Metadata API.
[sf:retrieve] package.xml - Unable to retrieve file for id 62 (IdeaThemeStatus). This Standard Value Set is either inaccessible or not supported in Metadata API.
[sf:retrieve] package.xml - Unable to retrieve file for id 63 (AddressStateCode). This Standard Value Set is either inaccessible or not supported in Metadata API.
[sf:retrieve] package.xml - Unable to retrieve file for id 64 (AddressCountryCode). This Standard Value Set is either inaccessible or not supported in Metadata API.
[sf:retrieve] package.xml - Unable to retrieve file for id 29 (InvoiceStatus). This Standard Value Set is either inaccessible or not supported in Metadata API.
[sf:retrieve] package.xml - Unable to retrieve file for id 70 (AccountContactMultiRoles). This Standard Value Set is either inaccessible or not supported in Metadata API.
[sf:retrieve] package.xml - Unable to retrieve file for id 71 (WorkOrderStatus). This Standard Value Set is either inaccessible or not supported in Metadata API.
[sf:retrieve] package.xml - Unable to retrieve file for id 72 (WorkOrderLineItemPriority). This Standard Value Set is either inaccessible or not supported in Metadata API.
[sf:retrieve] package.xml - Unable to retrieve file for id 73 (WorkOrderLineItemStatus). This Standard Value Set is either inaccessible or not supported in Metadata API.
[sf:retrieve] package.xml - Unable to retrieve file for id 37 (OrderType). This Standard Value Set is either inaccessible or not supported in Metadata API.
[sf:retrieve] package.xml - Can't retrieve non-customizable CustomObject named: UserLicense
```

Looks to be the same.

**Comment by pcon** [comment]
Feel free to remove anything that causes those errors.

While with the most recent change on the sfloess_266 branch does pull down the `sharingRules` folder, I am unable to push these changes back up.  I am getting this error

```
sharingRules/Account.sharingRules (Account.Chat_Window) -- Error: Not in package.xml
```

After looking in the `file-push` folder I can see that the `package.xml` file is missing any stanzas for any of the sharingRules.  I have a feeling that this is due to the files being pulled in but their extension not matching any of the extensions listed in the metadata file and so therefore Solenopsis pulls them in but doesn't add them to the `package.xml` because we can't find a match for the `*.sharingRules` files.  When you do the pull each of these sharing rules (ie `sharingGuestRule` and `sharingOwnerRule` come down as a `sharingRules` file.

**Comment by sfloess** [comment]
@pcon - ah the old "solved half the problem trick" courtesy of me!

I'll see what sorcery I can perform this weekend sir :)

Additionally, I'll see about performing the needful to resolve those error messages :)

**Comment by sfloess** [comment]
@pcon - the old "push" target does things a little different than some of the other *push targets...  I have the other stuff resolved (I believe) but will have to look a little more closely at the "push" target...  Almost there...

**Comment by sfloess** [comment]
@pcon - give the sfloess_266 branch another try sir...

**Comment by pcon** [comment]
Getting the following error when pushing

```text
[rh-sfdc:createPackageXmlChildren] Feb 03, 2020 9:03:17 AM org.apache.bsf.BSFManager exec
[rh-sfdc:createPackageXmlChildren] SEVERE: Exception :
[rh-sfdc:createPackageXmlChildren] java.security.PrivilegedActionException: org.apache.bsf.BSFException: BeanShell script error: Parse error at line 313, column 29.  Encountered: / BSF info: scriptdef_http://www.redhat.com/sfdc:createPackageXmlChildren at line: 0 column: columnNo
[rh-sfdc:createPackageXmlChildren] 	at java.security.AccessController.doPrivileged(Native Method)
[rh-sfdc:createPackageXmlChildren] 	at org.apache.bsf.BSFManager.exec(BSFManager.java:491)
[rh-sfdc:createPackageXmlChildren] 	at org.apache.tools.ant.util.optional.ScriptRunner.executeScript(ScriptRunner.java:98)
[rh-sfdc:createPackageXmlChildren] 	at org.apache.tools.ant.taskdefs.optional.script.ScriptDef.executeScript(ScriptDef.java:349)
[rh-sfdc:createPackageXmlChildren] 	at org.apache.tools.ant.taskdefs.optional.script.ScriptDefBase.execute(ScriptDefBase.java:51)
[rh-sfdc:createPackageXmlChildren] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
[rh-sfdc:createPackageXmlChildren] 	at sun.reflect.GeneratedMethodAccessor78.invoke(Unknown Source)
[rh-sfdc:createPackageXmlChildren] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[rh-sfdc:createPackageXmlChildren] 	at java.lang.reflect.Method.invoke(Method.java:498)
[rh-sfdc:createPackageXmlChildren] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
[rh-sfdc:createPackageXmlChildren] 	at org.apache.tools.ant.Task.perform(Task.java:348)
[rh-sfdc:createPackageXmlChildren] 	at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:68)
[rh-sfdc:createPackageXmlChildren] 	at net.sf.antcontrib.logic.IfTask.execute(IfTask.java:197)
[rh-sfdc:createPackageXmlChildren] 	at sun.reflect.GeneratedMethodAccessor107.invoke(Unknown Source)
[rh-sfdc:createPackageXmlChildren] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[rh-sfdc:createPackageXmlChildren] 	at java.lang.reflect.Method.invoke(Method.java:498)
[rh-sfdc:createPackageXmlChildren] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
[rh-sfdc:createPackageXmlChildren] 	at org.apache.tools.ant.TaskAdapter.execute(TaskAdapter.java:155)
[rh-sfdc:createPackageXmlChildren] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
[rh-sfdc:createPackageXmlChildren] 	at sun.reflect.GeneratedMethodAccessor78.invoke(Unknown Source)
[rh-sfdc:createPackageXmlChildren] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[rh-sfdc:createPackageXmlChildren] 	at java.lang.reflect.Method.invoke(Method.java:498)
[rh-sfdc:createPackageXmlChildren] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
[rh-sfdc:createPackageXmlChildren] 	at org.apache.tools.ant.Task.perform(Task.java:348)
[rh-sfdc:createPackageXmlChildren] 	at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:68)
[rh-sfdc:createPackageXmlChildren] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
[rh-sfdc:createPackageXmlChildren] 	at sun.reflect.GeneratedMethodAccessor78.invoke(Unknown Source)
[rh-sfdc:createPackageXmlChildren] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[rh-sfdc:createPackageXmlChildren] 	at java.lang.reflect.Method.invoke(Method.java:498)
[rh-sfdc:createPackageXmlChildren] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
[rh-sfdc:createPackageXmlChildren] 	at org.apache.tools.ant.Task.perform(Task.java:348)
[rh-sfdc:createPackageXmlChildren] 	at org.apache.tools.ant.taskdefs.MacroInstance.execute(MacroInstance.java:396)
[rh-sfdc:createPackageXmlChildren] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
[rh-sfdc:createPackageXmlChildren] 	at sun.reflect.GeneratedMethodAccessor78.invoke(Unknown Source)
[rh-sfdc:createPackageXmlChildren] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[rh-sfdc:createPackageXmlChildren] 	at java.lang.reflect.Method.invoke(Method.java:498)
[rh-sfdc:createPackageXmlChildren] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
[rh-sfdc:createPackageXmlChildren] 	at org.apache.tools.ant.Task.perform(Task.java:348)
[rh-sfdc:createPackageXmlChildren] 	at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:68)
[rh-sfdc:createPackageXmlChildren] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
[rh-sfdc:createPackageXmlChildren] 	at sun.reflect.GeneratedMethodAccessor78.invoke(Unknown Source)
[rh-sfdc:createPackageXmlChildren] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[rh-sfdc:createPackageXmlChildren] 	at java.lang.reflect.Method.invoke(Method.java:498)
[rh-sfdc:createPackageXmlChildren] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
[rh-sfdc:createPackageXmlChildren] 	at org.apache.tools.ant.Task.perform(Task.java:348)
[rh-sfdc:createPackageXmlChildren] 	at org.apache.tools.ant.taskdefs.MacroInstance.execute(MacroInstance.java:396)
[rh-sfdc:createPackageXmlChildren] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
[rh-sfdc:createPackageXmlChildren] 	at sun.reflect.GeneratedMethodAccessor78.invoke(Unknown Source)
[rh-sfdc:createPackageXmlChildren] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[rh-sfdc:createPackageXmlChildren] 	at java.lang.reflect.Method.invoke(Method.java:498)
[rh-sfdc:createPackageXmlChildren] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
[rh-sfdc:createPackageXmlChildren] 	at org.apache.tools.ant.Task.perform(Task.java:348)
[rh-sfdc:createPackageXmlChildren] 	at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:68)
[rh-sfdc:createPackageXmlChildren] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
[rh-sfdc:createPackageXmlChildren] 	at sun.reflect.GeneratedMethodAccessor78.invoke(Unknown Source)
[rh-sfdc:createPackageXmlChildren] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[rh-sfdc:createPackageXmlChildren] 	at java.lang.reflect.Method.invoke(Method.java:498)
[rh-sfdc:createPackageXmlChildren] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
[rh-sfdc:createPackageXmlChildren] 	at org.apache.tools.ant.Task.perform(Task.java:348)
[rh-sfdc:createPackageXmlChildren] 	at org.apache.tools.ant.taskdefs.MacroInstance.execute(MacroInstance.java:396)
[rh-sfdc:createPackageXmlChildren] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
[rh-sfdc:createPackageXmlChildren] 	at sun.reflect.GeneratedMethodAccessor78.invoke(Unknown Source)
[rh-sfdc:createPackageXmlChildren] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[rh-sfdc:createPackageXmlChildren] 	at java.lang.reflect.Method.invoke(Method.java:498)
[rh-sfdc:createPackageXmlChildren] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
[rh-sfdc:createPackageXmlChildren] 	at org.apache.tools.ant.Task.perform(Task.java:348)
[rh-sfdc:createPackageXmlChildren] 	at org.apache.tools.ant.Target.execute(Target.java:435)
[rh-sfdc:createPackageXmlChildren] 	at org.apache.tools.ant.Target.performTasks(Target.java:456)
[rh-sfdc:createPackageXmlChildren] 	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
[rh-sfdc:createPackageXmlChildren] 	at org.apache.tools.ant.Project.executeTarget(Project.java:1376)
[rh-sfdc:createPackageXmlChildren] 	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
[rh-sfdc:createPackageXmlChildren] 	at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
[rh-sfdc:createPackageXmlChildren] 	at org.apache.tools.ant.Main.runBuild(Main.java:853)
[rh-sfdc:createPackageXmlChildren] 	at org.apache.tools.ant.Main.startAnt(Main.java:235)
[rh-sfdc:createPackageXmlChildren] 	at org.apache.tools.ant.Main.start(Main.java:198)
[rh-sfdc:createPackageXmlChildren] 	at org.apache.tools.ant.Main.main(Main.java:286)
[rh-sfdc:createPackageXmlChildren] Caused by: org.apache.bsf.BSFException: BeanShell script error: Parse error at line 313, column 29.  Encountered: / BSF info: scriptdef_http://www.redhat.com/sfdc:createPackageXmlChildren at line: 0 column: columnNo
[rh-sfdc:createPackageXmlChildren] 	at bsh.util.BeanShellBSFEngine.eval(Unknown Source)
[rh-sfdc:createPackageXmlChildren] 	at bsh.util.BeanShellBSFEngine.exec(Unknown Source)
[rh-sfdc:createPackageXmlChildren] 	at org.apache.bsf.BSFManager$6.run(BSFManager.java:493)
[rh-sfdc:createPackageXmlChildren] 	... 76 more
[rh-sfdc:createPackageXmlChildren] 

BUILD FAILED
/usr/share/solenopsis/ant/1.1/solenopsis-build.xml:228: The following error occurred while executing this line:
/usr/share/solenopsis/ant/1.1/util/sfdc-util.xml:3504: The following error occurred while executing this line:
/usr/share/solenopsis/ant/1.1/util/sfdc-util.xml:2967: The following error occurred while executing this line:
/usr/share/solenopsis/ant/1.1/util/sfdc-util.xml:3005: org.apache.bsf.BSFException: BeanShell script error: Parse error at line 313, column 29.  Encountered: / BSF info: scriptdef_http://www.redhat.com/sfdc:createPackageXmlChildren at line: 0 column: columnNo
	at bsh.util.BeanShellBSFEngine.eval(Unknown Source)
	at bsh.util.BeanShellBSFEngine.exec(Unknown Source)
	at org.apache.bsf.BSFManager$6.run(BSFManager.java:493)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.apache.bsf.BSFManager.exec(BSFManager.java:491)
	at org.apache.tools.ant.util.optional.ScriptRunner.executeScript(ScriptRunner.java:98)
	at org.apache.tools.ant.taskdefs.optional.script.ScriptDef.executeScript(ScriptDef.java:349)
	at org.apache.tools.ant.taskdefs.optional.script.ScriptDefBase.execute(ScriptDefBase.java:51)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
	at sun.reflect.GeneratedMethodAccessor78.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:68)
	at net.sf.antcontrib.logic.IfTask.execute(IfTask.java:197)
	at sun.reflect.GeneratedMethodAccessor107.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.TaskAdapter.execute(TaskAdapter.java:155)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
	at sun.reflect.GeneratedMethodAccessor78.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:68)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
	at sun.reflect.GeneratedMethodAccessor78.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.taskdefs.MacroInstance.execute(MacroInstance.java:396)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
	at sun.reflect.GeneratedMethodAccessor78.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:68)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
	at sun.reflect.GeneratedMethodAccessor78.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.taskdefs.MacroInstance.execute(MacroInstance.java:396)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
	at sun.reflect.GeneratedMethodAccessor78.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:68)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
	at sun.reflect.GeneratedMethodAccessor78.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.taskdefs.MacroInstance.execute(MacroInstance.java:396)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
	at sun.reflect.GeneratedMethodAccessor78.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:435)
	at org.apache.tools.ant.Target.performTasks(Target.java:456)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1376)
	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
	at org.apache.tools.ant.Main.runBuild(Main.java:853)
	at org.apache.tools.ant.Main.startAnt(Main.java:235)
	at org.apache.tools.ant.Main.start(Main.java:198)
	at org.apache.tools.ant.Main.main(Main.java:286)

Total time: 3 minutes 54 seconds
```

**Comment by sfloess** [comment]
@pcon - arg!  OK that I definitely didn't get yesterday.   I'll dig in...

**Comment by sfloess** [comment]
Note to self:  Failure was a result of `delta-push`

**Comment by sfloess** [comment]
@pcon - [face palm](https://github.com/solenopsis/Solenopsis/blob/sfloess_266/ant/1.1/util/sfdc-util.xml#L518)

```java
return;~/.solenopsis/env/qa/sharingRules/
```

Looks like the middle mouse button trick!

**Comment by sfloess** [comment]
@pcon - give it another try sir...
